import {
  Droplets,
  SprayCan,
  FlaskConical,
  Sun,
  Smile,
  Palette,
  Brush,
  Eye,
  Scissors,
  Flower2,
  Flower,
  Bath,
  ShowerHead,
  Wind,
  Sparkles,
  Wand2,
  Heart,
  Hand,
  Gem,
  Layers,
  Moon,
  Zap,
  Star,
  Circle,
  Aperture,
  Clock,
  Feather,
  Snowflake,
  Leaf,
  Shield,
  GlassWater,
  Droplet,
  Paintbrush,
  PaintBucket,
  User,
  Home,
  Tag,
  ShoppingCart,
  Megaphone,
  Mail,
  MessageSquare,
  Gift,
  Activity,
  Link2,
  ShoppingBag,
  CreditCard,
  Truck,
  Package,
  Search,
  ClipboardList,
  Check,
  X,
  Users,
  UserPlus,
  type LucideIcon,
} from "lucide-react";

// T-47: Ikon kategori disimpan sebagai NAMA icon Lucide (string) di DB.
// Komponen ini memetakan nama → komponen Lucide untuk render dinamis.
const ICON_MAP: Record<string, LucideIcon> = {
  droplets: Droplets,
  "spray-can": SprayCan,
  "flask-conical": FlaskConical,
  sun: Sun,
  smile: Smile,
  palette: Palette,
  brush: Brush,
  eye: Eye,
  scissors: Scissors,
  "flower-2": Flower2,
  flower: Flower,
  bath: Bath,
  "shower-head": ShowerHead,
  wind: Wind,
  sparkles: Sparkles,
  "wand-2": Wand2,
  heart: Heart,
  hand: Hand,
  gem: Gem,
  layers: Layers,
  moon: Moon,
  zap: Zap,
  star: Star,
  circle: Circle,
  aperture: Aperture,
  clock: Clock,
  feather: Feather,
  snowflake: Snowflake,
  leaf: Leaf,
  shield: Shield,
  "glass-water": GlassWater,
  droplet: Droplet,
  paintbrush: Paintbrush,
  "paint-bucket": PaintBucket,
  user: User,
  home: Home,
  tag: Tag,
  "shopping-cart": ShoppingCart,
  megaphone: Megaphone,
  mail: Mail,
  "message-square": MessageSquare,
  gift: Gift,
  activity: Activity,
  "link-2": Link2,
  "shopping-bag": ShoppingBag,
  "credit-card": CreditCard,
  truck: Truck,
  package: Package,
  search: Search,
  clipboard: ClipboardList,
  check: Check,
  x: X,
  users: Users,
  "user-plus": UserPlus,
};

export const CATEGORY_ICON_NAMES = Object.keys(ICON_MAP);

// T-47: Daftar icon yang disarankan untuk kategori (tampil pertama di pemilih)
export const SUGGESTED_ICONS = [
  "droplets", "spray-can", "flask-conical", "sun", "smile", "palette",
  "brush", "eye", "flower-2", "flower", "bath", "shower-head",
  "wind", "sparkles", "wand-2", "heart", "glass-water", "leaf",
];

export function CategoryIcon({
  name,
  className,
  size,
}: {
  name?: string | null;
  className?: string;
  size?: number;
}) {
  const Icon = name ? ICON_MAP[name] : undefined;
  if (!Icon) return <Circle className={className} size={size ?? 16} />;
  return <Icon className={className} size={size ?? 16} />;
}